### ISSUE TITLE
Entering the key at https://smartlike.org/login/ causes nothing to happen.

### ISSUE THREAD

**Issue by saper** [smartlike-org/smartlike#7]
User-Agent: Mozilla/5.0 (X11; FreeBSD amd64; rv:93.0) Gecko/20100101 Firefox/93.0

1. I have a previously created account with the key stored in my password manager.
2. I go to https://smartlike.org/login/
3. **Enter or an account key:** message appears
4. I paste my password
5. Stars appear
6. I press submit
7. Nothing happens.

In the browser console I can see POST  a request going out every time I click "Submit"

POST https://smartlike.org/network

A response comes with 200 status code and some JSON that contains, among others, `status: ok` as well as my nickname somewhere in the `dns` sub-tree.

No errors are visible in the console as of now (except for one warning earlier `Cookie “theme” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`, probably unrelated.)

**Comment by saper** [comment]
Okay, it works with Chromium. (and I get an additional popup to ask if I want to login, register or use "local account")

**Comment by vadim-frolov** [comment]
/login path will only used by the extension from now on. Onsite logins are performed with modals without leaving the current page.
